# For more information: https://laravel.com/docs/sail
version: '3'
services:
    php:
        build:
            context: ./docker/php/8.1
            dockerfile: Dockerfile
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            # - '${APP_PORT:-80}:80'
            - '${HMR_PORT:-8080}:8080'
        environment:
            LARAVEL_SAIL: 1
            APP_NAME: ${APP_NAME}
            APP_DEBUG: 'false'
            APP_URL: https://${TRAEFIK_URL}
            DB_CONNECTION: mysql
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
            REDIS_HOST: ${REDIS_HOST}
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            REDIS_PORT: ${REDIS_PORT}
        volumes:
            - '.:/var/www/html'
            - './docker/php/8.1/php.ini:/usr/local/etc/php/php.ini'
        networks:
            - traefik
    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
            args:
                - WWWGROUP='${WWWGROUP}'
                - WWWUSER='${WWWUSER}'
                - PHP_UPSTREAM_CONTAINER=${PHP_HOST}
                - PHP_UPSTREAM_PORT=${PHP_PORT}
                #- PHP_HEALTHCHECK_CONTAINER=${APP_SERVICE:-php}
                # - PHP_HEALTHCHECK_PORT=9091
                - http_proxy
                # - https_proxy
                - no_proxy
        volumes:
            - .:/var/www/html
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/ssl/:/etc/nginx/ssl
        networks:
            - traefik
        depends_on:
            - php
        healthcheck:
            test: ['CMD', 'curl', '-f', 'nginx/_healthcheck/nginx']
            retries: 3
            timeout: 5s
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.${TRAEFIK_ROUTER}.rule=Host(`${TRAEFIK_URL}`)"
            - "traefik.http.routers.${TRAEFIK_ROUTER}.entrypoints=websecure"
            - "traefik.http.services.${TRAEFIK_ROUTER}.loadbalancer.server.port=${TRAEFIK_PORT}"
            - "traefik.http.routers.${TRAEFIK_ROUTER}.service=${TRAEFIK_ROUTER}"
            - "traefik.http.routers.${TRAEFIK_ROUTER}.tls=true"
            - "traefik.http.routers.${TRAEFIK_ROUTER}.tls.certresolver=leresolver"

networks:
    traefik:
        external: true
